### ISSUE TITLE
This Error on Windows

### ISSUE THREAD

**Issue by Princeyadav05** [manojmj92/subtitle-downloader#50]
I'm getting this error on windows,
Can you reproduce?

![screenshot 18](https://user-images.githubusercontent.com/22894003/30865333-e7ee5fcc-a2f3-11e7-98b5-f683a265d0fb.png)

**Comment by Akshay-parashar** [comment]
Someone has already stated this issue,and a workaround for it as well to be added in the README. What you can do is instead of placing the subtitle-dowloader.py file in the C drive put it elsewhere where it does't  requires root permission to write in the log file. (put it another drive) Update that file location in the subtitle.cmd file accordingly.
